alnviz_job: 
  title: Alignment Viewer
  hidden: false
  code: ALVI
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
    - name: reducedfasta
      title: Reduced Fasta
      title_long: Show result
      forwardsections:
    - name: fasta
      title: Fasta
      title_long: Show result
      forwardsections:
  forwarding_acceptances:
      type: 4
