blammer_job: 
  title: Blammer
  hidden: false
  code: BLAM
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
  forwarding_acceptances:
     type: 64
  forwarding_emission:
      type: 6
      format: S,MSA

