clubsubp_job: 
  title: ClubSub-P
  hidden: false
  code: CLUB
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
        - name: forward
          title: Forward
          title_long: Forward result
