gcview_job: 
  title: Gcview
  hidden: false
  code: GCVI
  resultsections:  
    - name: results
      title: Group View
      title_long: Show results in Group View
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_taxonomy
      title: Taxonomy View
      title_long: Show results in Taxonomy View
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
  forwarding_acceptances:
     type: 11
#    - name: results_tab3
#      title:
#      title_long:
#      forwardsections:
#      - name: forward
#        title: Forward
#        title_long: Forward results
