gcview_job: 
  title: Gcview
  hidden: false
  code: GCVI
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_taxonomy
      title: Result Taxonomy
      title_long: Show taxonomy result
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_tab3
      title: Result Tab3
      title_long: Show results of tab3
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
