gcview_job: 
  title: Gcview
  hidden: false
  code: GCVI
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
    - name: results_taxonomy
      title: Result Taxonomy
      title_long: Show taxonomy result
      forwardsections:
