hhalign_job: 
  title: HHalign
  hidden: false
  code: HHAL
  resultsections:  
    - name: results
      title: Global alignment
      title_long: Global alignment
      forwardsections:
  forwarding_acceptances:
      type: 4
