hhblits_job:
  title: HHblits
  hidden: false
  code: HHBL
  resultsections:  
    - name: results
      title: Results
      title_long: Show results in alignment view
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: histograms
      title: Histogram
      title_long: Show results in profile histogram view
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: showalign
      title: Show alignment
      title_long: Show alignment constructed by HHblast
      forwardsections:
      