hhblits_job:
  title: HHblits
  hidden: false
  code: HHBL
  resultsections:  
    - name: results
      title: Results
      title_long: Show results in alignment view
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
      forwardhhmsections:
      - name: forwardhhm
        title: Forward HMM
        title_long: Forward query HMM
    - name: histograms
      title: Histogram
      title_long: Show results in profile histogram view
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: reducedalign
      title: Reduced alignment
      title_long: Show reduced alignment
    - name: representativealign
      title: Representative alignment
      title_long: Show representative alignment
    - name: fullalign
      title: Full alignment
      title_long: Show full alignment