hhfrag_job:
  title: HHfrag
  hidden: false
  code: HFRG
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
  forwarding_acceptances:
      type: 1

