hhrepid_job: 
  title: HHrepID
  hidden: false
  code: HHID
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
        forwardmsasections:
      - name: forwardmsa
        title: Forward MSA
        title_long: Forward query MSA
    - name: results_showquery
      title: Show query alignment
      title_long: Show or edit the query alignment constructed by HHrep
      forwardsections:
  forwarding_acceptances:
     type: 5

