hmmer3_job: 
  title: HMMER3
  hidden: false
  code: HMR3
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
    - name: results_fasta
      title: FASTA alignment
      title_long: Show FASTA alignment
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_stockholm
      title: STOCKHOLM alignment
      title_long: Show STOCKHOLM alignment
      forwardsections:
    - name: results_domtbl
      title: Domain table
      title_long: Show Domain table
      forwardsections:
  forwarding_emission:
      type: 5
      format: CLUSTAL
  forwarding_acceptances:
     type: 4 
