muscle_job: 
  title: MUSCLE
  hidden: false
  code: MUSC
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
  forwarding_emission:
      type: 4
      format: fas
  forwarding_acceptances:
      type: 3
