patsearch_job: 
  title: Pattern Search
  hidden: false
  code: PATS
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
  forwarding_emission:
      type: 3
      format: SEQ
