pcoils_job:
  title: PCOILS
  hidden: false
  code: COIL
  resultsections:
    - name: results_numerical
      title: Numerical Results
      title_long: Show numerical result
      forwardsections:
    - name: results
      title: Graphical Results
      title_long: Show graphical results
      forwardsections:

