pcoils_job:
  title: COILS/PCOILS
  hidden: false
  code: COIL
  resultsections:
    - name: results
      title: Results
      title_long: Show results
      forwardsections:
    - name: results_numerical
      title: Numerical Results
      title_long: Show numerical results
      forwardsections:

