prot_blast_job:
  title: Protein BLAST
  hidden: false
  code: PROB
  resultsections:
    - name: results
      title: Results
      title_long: Show results
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_alignment
      title: Alignment
      title_long: Show alignment of all hits
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_hitlist
      title: Graphical Hitlist
      title_long: Show graphical hitlist
      forwardsections:
    - name: results_eval_graph
      title: E-value distribution
      title_long: Show E-value distribution
      forwardsections:
