psi_blastp_job:
  title: PSI-BLASTP
  hidden: false
  code: PSIBP
  resultsections:
    - name: results
      title: Results
      title_long: Show results
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_alignment
      title: Alignment
      title_long: Show alignment of all hits
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
    - name: results_eval_graph
      title: E-value distribution
      title_long: Show E-value distribution
      forwardsections:
  forwarding_acceptances:
     type: 5
  forwarding_emission:
      type: 71
      format: MSA
