quick2_d_job: 
  title: Quick2D
  hidden: false
  code: Q2D
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
  forwarding_acceptances:
      type: 5
