reformat_job: 
  title: Reformat
  hidden: false
  code: FORM
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
  forwarding_acceptances:
      type: 5
