repper_job: 
  title: REPPER
  hidden: false
  code: REPP
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
  forwarding_acceptances:
     type: 5

