rnasehpred_job: 
  title: RNAseHpred
  hidden: false
  code: RNH
  resultsections:  
    - name: results
      title: Results
      title_long: Show results in alignment view
      forwardsections:
      - name: mergeali
        title: Merge Q/T alignments
        title_long: Merge Query/Template Multiple Alignments
      - name: forward
        title: Forward MSA
        title_long: Forward query MSA
    - name: histograms
      title: Histogram
      title_long: Show results in profile histogram view
      forwardsections:
      - name: mergeali
        title: Merge Q/T alignments
        title_long: Merge Query/Template Multiple Alignments
    - name: showalign
      title: Show query alignment
      title_long: Show or edit the query alignment constructed by HHpred
      forwardsections:

hhmergeali_job:
  title: RNAseHpred mergeali
  hidden: false
  code: RNHMA
