seq2gi_job: 
  title: Extract GIs
  hidden: false
  code: S2GI
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
      - name: forward
        title: Forward
        title_long: Forward results
