--- 
- name: hhpred
  title: HHpred
  title_long: HHpred - Homology detection & structure prediction by HMM-HMM comparison
  section: search
  updated: July, 2012
  version: HHsuite-2.0.16mod 
  active: 
  - member
  - internal
  - external
- name: prot_blast
  title: ProtBLAST
  title_long: Protein BLAST
  section: search
  updated: December, 2010
  version: Blast 2.2.26
  active: 
  - member
  - internal
  - external
- name: modeller
  title: Modeller
  title_long: Modeller
  section: tertstruct
  updated: July, 2015
  version: 9.15
  active: 
  - member
  - internal
  - external
- name: hhrep
  title: HHrep
  title_long: HHrep - de novo protein repeat detection by HMM-HMM comparison
  section: seqanal
  updated: May, 2012
  version: HHsuite-2.0.16mod
  active: 
  - member
  - internal
  - external
- name: hhsenser
  title: HHsenser
  title_long: HHsenser - exhaustive intermediate profile search using HMM-HMM comparison
  section: search
  updated: November, 2011
  version: Not HHsuite
  active: 
  - member
  - internal
  - external
- name: psi_blast
  title: PSI-BLAST
  title_long: PSI-BLAST
  section: search
  updated: December, 2010
  version: Blast 2.2.26
  active: 
  - member
  - internal
  - external
- name: psi_blastp
  title: PSI-BLASTP
  title_long: PSI-BLASTP
  section: search
  updated: February, 2015
  version: Blast 2.2.23
  active: 
  - member
  - internal
- name: reformat
  title: Reformat
  title_long: Reformat
  section: utils
  updated: January, 2012
  version: 1.3
  active: 
  - member
  - internal
  - external
- name: sixframe
  title: 6FrameTranslation
  title_long: 6 Frame Translation
  section: utils
  updated: December, 2010
  version: 1.0
  active: 
  - member
  - internal
  - external
- name: seq2gi
  title: Extract GIs
  title_long: Extract GIs
  section: utils
  updated: December, 2010
  version: 1.0
  active: 
  - member
  - internal
  - external
- name: quick2_d
  title: Quick2D
  title_long: Quick2D
  section: secstruct
  updated: March, 2012
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: msaprobs
  title: MSAProbs
  title_long: MSAProbs
  section: alignment
  updated: April, 2013
  version: 0.9.7
  active: 
  - member
  - internal
  - external
- name: clustalw
  title: Clustal Omega
  title_long: Clustal Omega
  section: alignment
  updated: March, 2013
  version: 2.1, Omega 0.2.0
  active: 
  - member
  - internal
  - external
- name: muscle
  title: MUSCLE
  title_long: MUSCLE
  section: alignment
  updated: July, 2015
  version: 3.8.31
  active: 
  - member
  - internal
  - external
- name: probcons
  title: ProbCons
  title_long: ProbCons
  section: alignment
  updated: Feburary, 2011
  version: 1.12
  active: 
  - member
  - internal
  - external
- name: mafft
  title: MAFFT
  title_long: MAFFT
  section: alignment
  updated: July, 2015
  version: 7.221
  active: 
  - member
  - internal
  - external
- name: blammer
  title: Blammer
  title_long: Blammer
  section: alignment
  updated: December, 2010
  version: n.A.
  active: 
  - member
  - internal
  - external
- name: hhalign
  title: HHalign
  title_long: HHalign
  section: alignment
  updated: May, 2012
  version: HHsuite-2.0.16mod
  active: 
  - member
  - internal
  - external
- name: patsearch
  title: PatternSearch
  title_long: Pattern Search
  section: search
  updated: February, 2012
  version: 1.1
  active: 
  - member
  - internal
  - external
- name: hmmer3
  title: HMMER3
  title_long: HMMER3
  section: search
  updated: August, 2015
  version: 3.1b2
  active:
  - member
  - internal
  - external
- name: ancescon
  title: ANCESCON
  title_long: ANCESCON
  section: classification
  updated: August, 2011
  version: n.A.
  active: 
  - member
  - internal
  - external
- name: clans
  title: CLANS
  title_long: CLANS
  section: classification
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: hhcluster
  title: HHcluster
  title_long: HHcluster - Galaxy of Folds
  section: classification
  updated: May, 2012
  version: HHsuite-2.0.16mod
  active: 
  - mpi
  - internal
  - external
- name: kalign
  title: Kalign
  title_long: Kalign
  section: alignment
  updated: December, 2010
  version: 2.04
  active: 
  - member
  - internal
  - external
- name: phylip
  title: PHYLIP-NEIGHBOR
  title_long: PHYLIP-NEIGHBOR
  section: classification
  updated: July, 2015
  version: 3.696
  active: 
  - member
  - internal
  - external
- name: alnviz
  title: AlignmentViewer
  title_long: Alignment Viewer
  section: alignment
  updated: August, 2011
  version: Jalview 3.7
  active: 
  - member
  - internal
  - external
- name: aln2plot
  title: Aln2Plot
  title_long: Aln2Plot
  section: seqanal
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: frpred
  title: FRpred
  title_long: FRpred
  section: seqanal
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: tprpred
  title: TPRpred
  title_long: TPRpred
  section: seqanal
  updated: February, 2011 
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: pcoils
  title: COILS/PCOILS
  title_long: COILS/PCOILS
  section: seqanal
  updated: December, 2010 
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: marcoil
  title: MARCOIL
  title_long: MARCOIL
  section: seqanal
  updated: May, 2011
  version: 1.0
  active:
  - member
  - internal
  - external
- name: repper
  title: REPPER
  title_long: REPPER - Detecting regions with short gapless REPeats in protein sequences
  section: seqanal
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: gi2seq
  title: RetrieveSeq
  title_long: RetrieveSeq
  section: utils
  updated: November, 2011
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: gi2pro
  title: GI2Promoter
  title_long: GI2Promoter
  section: utils
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: backtrans
  title: Backtranslator
  title_long: Backtranslator
  section: utils
  updated: December, 2010 
  version: 1.0
  active: 
  - member
  - internal
  - external
- name: blastclust
  title: BLASTclust
  title_long: BLASTclust
  section: classification
  updated: December, 2010
  version: Blast 2.2.26
  active: 
  - member
  - internal
  - external
- name: ali2d
  title: Ali2D
  title_long: Ali2D
  section: secstruct
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: hhfilter
  title: HHfilter
  title_long: HHfilter
  section: utils
  updated: July, 2012
  version: HHsuite-2.0.16mod
  active: 
  - member
  - internal
  - external
- name: t_coffee
  title: TCoffee
  title_long: TCoffee
  section: alignment
  updated: July, 2015
  version: 11.00
  active: 
  - member
  - internal
  - external
- name: hhomp
  title: HHomp
  title_long: HHomp - Homology detection of OMPs by HMM-HMM comparison
  section: secstruct
  updated: December, 2010
  version: hh 1.2.5, blast 2.2.26
  active: 
  - member
  - internal
  - external
- name: peaks
  title: Peaks
  title_long: Peaks
  section: utils
  updated: December, 2010
  version: n.a.
  active: 
  - internal
- name: hhrepid
  title: HHrepID
  title_long: HHrepID
  section: seqanal
  updated: July, 2012
  version: HHsuite-2.0.16mod
  active: 
  - member
  - internal
  - external
- name: dataa2
  title: DATAA2
  title_long: Domain Annotation of Trimeric Autotransporter Adhesins
  section: classification
  updated: January, 2015
  version: 0.1.0
  active: 
  - member
  - internal
- name: dataa
  title: daTAA
  title_long: domain annotation of Trimeric Autotransporter Adhesins
  section: classification
  updated: December, 2010
  version: 0.1.4 
  active: 
  - member
  - internal
  - external
- name: hhblits
  title: HHblits
  title_long: HHblits - Homology detection by iterative HMM-HMM comparison
  section: search
  updated: May, 2012
  version: HHsuite-2.0.16mod
  active: 
  - hhgroup
  - member
  - internal
  - external
- name: cs_blast
  title: CS-BLAST
  title_long: CS-BLAST/ CSI-BLAST
  section: search
  updated: December, 2012
  version: 2.2.3
  active: 
  - member
  - internal
  - external
- name: simshift
  title: SimShiftDB
  title_long: SimShiftDB
  section: search
  updated: February, 2012
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: ancient_dict
  title: DAP
  title_long: DAP - Dictionary of Ancestral Peptides
  section: classification
  updated: n.a.
  version: n.a.
  active: 
  - dap
- name: samcc
  title: SamCC
  title_long: Four-helical bundle analysis tool
  section: tertstruct
  updated: December, 2010
  version: 4.0 
  active: 
  - member
  - internal
  - external
- name: clubsubp
  title: ClubSub-P
  title_long: Cluster-based Subcellular localization prediction
  section: classification
  updated: July, 2011
  version: n.a.
  active:
  - member 
  - internal
  - external
- name: gcview
  title: GCView
  title_long: Genomic Context Viewer
  section: classification
  updated: December, 2010
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: bfit
  title: bFit
  title_long: bFit
  section: tertstruct
  updated: September, 2011
  version: n.a.
  active: 
  - member
  - internal
  - external
- name: hhfrag
  title: HHfrag
  title_long: HHfrag -- Dynamic fragment libraries and prediction of torsion angles
  section: tertstruct
  updated: September, 2009
  version: n.a.
  active:
  - member
  - internal
  - external
- name: hamppred
  title: HAMPpred
  title_long: HAMPpred - Description needed
  section: classification
  updated: November, 2013
  version: n.a.
  active: 
  - member
  - internal
- name: rnasehpred
  title: RNAseHpred
  title_long: RNAseHpred - Description needed
  section: classification
  updated: April, 2015
  version: n.a.
  active: 
  - member
  - internal

