--- 
- name: hhpred
  title: HHpred
  title_long: HHpred - Homology detection & structure prediction by HMM-HMM comparison
  section: search
  active: 
  - member
  - internal
  - external
- name: prot_blast
  title: ProtBLAST
  title_long: Protein BLAST
  section: search
  active: 
  - member
  - internal
  - external
- name: modeller
  title: Modeller
  title_long: Modeller
  section: tertstruct
  active: 
  - member
  - internal
  - external
- name: hhrep
  title: HHrep
  title_long: HHrep - de novo protein repeat detection by HMM-HMM comparison
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: hhsenser
  title: HHsenser
  title_long: HHsenser - exhaustive intermediate profile search using HMM-HMM comparison
  section: search
  active: 
  - member
  - internal
  - external
- name: psi_blast
  title: PSI-BLAST
  title_long: PSI-BLAST
  section: search
  active: 
  - member
  - internal
  - external
- name: reformat
  title: Reformat
  title_long: Reformat
  section: utils
  active: 
  - member
  - internal
  - external
- name: sixframe
  title: 6FrameTranslation
  title_long: 6 Frame Translation
  section: utils
  active: 
  - member
  - internal
  - external
- name: seq2gi
  title: Extract GIs
  title_long: Extract GIs
  section: utils
  active: 
  - member
  - internal
  - external
- name: quick2_d
  title: Quick2D
  title_long: Quick2D
  section: secstruct
  active: 
  - member
  - internal
  - external
- name: clustalw
  title: ClustalW
  title_long: ClustalW
  section: alignment
  active: 
  - member
  - internal
  - external
- name: muscle
  title: MUSCLE
  title_long: MUSCLE
  section: alignment
  active: 
  - member
  - internal
  - external
- name: probcons
  title: ProbCons
  title_long: ProbCons
  section: alignment
  active: 
  - member
  - internal
  - external
- name: mafft
  title: MAFFT
  title_long: MAFFT
  section: alignment
  active: 
  - member
  - internal
  - external
- name: blammer
  title: Blammer
  title_long: Blammer
  section: alignment
  active: 
  - member
  - internal
  - external
- name: hhalign
  title: HHalign
  title_long: HHalign
  section: alignment
  active: 
  - member
  - internal
  - external
- name: nuc_blast
  title: NucBLAST
  title_long: Nucleotide BLAST
  section: search
  active: 
  - member
  - internal
  - external
- name: patsearch
  title: PatternSearch
  title_long: Pattern Search
  section: search
  active: 
  - member
  - internal
  - external
- name: fast_hmmer
  title: FHMMER
  title_long: FastHMMER
  section: search
  active: 
  - member
  - internal
  - external
- name: ancescon
  title: ANCESCON
  title_long: ANCESCON
  section: classification
  active: 
  - member
  - internal
  - external
- name: clans
  title: CLANS
  title_long: CLANS
  section: classification
  active: 
  - member
  - internal
  - external
- name: hhcluster
  title: HHcluster
  title_long: HHcluster - Galaxy of Folds
  section: classification
  active: 
  - mpi
  - internal
  - external
- name: kalign
  title: Kalign
  title_long: Kalign
  section: alignment
  active: 
  - member
  - internal
  - external
- name: phylip
  title: PHYLIP-NEIGHBOR
  title_long: PHYLIP-NEIGHBOR
  section: classification
  active: 
  - member
  - internal
  - external
- name: alnviz
  title: AlignmentViewer
  title_long: Alignment Viewer
  section: alignment
  active: 
  - member
  - internal
  - external
- name: aln2plot
  title: Aln2Plot
  title_long: Aln2Plot
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: frpred
  title: FRpred
  title_long: FRpred
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: tprpred
  title: TPRpred
  title_long: TPRpred
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: pcoils
  title: COILS/PCOILS
  title_long: COILS/PCOILS
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: repper
  title: REPPER
  title_long: REPPER - Detecting regions with short gapless REPeats in protein sequences
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: gi2seq
  title: RetrieveSeq
  title_long: RetrieveSeq
  section: utils
  active: 
  - member
  - internal
  - external
- name: gi2pro
  title: GI2Promoter
  title_long: GI2Promoter
  section: utils
  active: 
  - member
  - internal
  - external
- name: backtrans
  title: Backtranslator
  title_long: Backtranslator
  section: utils
  active: 
  - member
  - internal
  - external
- name: blastclust
  title: BLASTclust
  title_long: BLASTclust
  section: classification
  active: 
  - member
  - internal
  - external
- name: ali2d
  title: Ali2D
  title_long: Ali2D
  section: secstruct
  active: 
  - member
  - internal
  - external
- name: hhfilter
  title: HHfilter
  title_long: HHfilter
  section: utils
  active: 
  - member
  - internal
  - external
- name: t_coffee
  title: TCoffee
  title_long: TCoffee
  section: alignment
  active: 
  - member
  - internal
  - external
- name: hhomp
  title: HHomp
  title_long: HHomp - Homology detection of OMPs by HMM-HMM comparison
  section: secstruct
  active: 
  - member
  - internal
  - external
- name: peaks
  title: Peaks
  title_long: Peaks
  section: utils
  active: 
  - internal
- name: hhrepid
  title: HHrepID
  title_long: HHrepID
  section: seqanal
  active: 
  - member
  - internal
  - external
- name: dataa
  title: daTAA
  title_long: domain annotation of Trimeric Autotransporter Adhesins
  section: classification
  active: 
  - member
  - internal
  - external
- name: hhblast
  title: HHblast
  title_long: HHblast - Homology detection by iterative HMM-HMM comparison
  section: search
  active: 
  - hhgroup
  - internal
- name: cs_blast
  title: CS-BLAST
  title_long: CS-BLAST/ CSI-BLAST
  section: search
  active: 
  - member
  - internal
  - external
- name: simshift
  title: SimShiftDB
  title_long: SimShiftDB
  section: search
  active: 
  - member
  - internal
  - external
- name: ancient_dict
  title: DAP
  title_long: DAP - Dictionary of Ancestral Peptides
  section: classification
  active: 
  - dap
  - member
  - internal
  - external
- name: samcc
  title: SamCC
  title_long: Four-helical bundle analysis tool
  section: tertstruct
  active: 
  - member
  - internal
  - external
