tprpred_job: 
  title: TPRpred
  hidden: false
  code: TPRP
  resultsections:  
    - name: results
      title: Results
      title_long: Show result
      forwardsections:
  forwarding_acceptances:
     type: 1

